# fly.toml app configuration file generated for rocknite-login on 2025-07-05T12:00:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rocknite-login'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 1234
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
